// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebStore.Database;

#nullable disable

namespace WebStore.Database.Migrations
{
    [DbContext(typeof(WebStoreContext))]
    [Migration("20230505185548_ProductSeeding")]
    partial class ProductSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("WebStore.Core.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("718ebdc0-47c6-40e5-90ce-58c824194d5f"),
                            Description = "Premium, delicious, kibble made from free range, grass-fed horses. 1 kilogram of kibble.",
                            Name = "Dry Food",
                            Price = 12.34m
                        },
                        new
                        {
                            Id = new Guid("52dd8d7b-761c-4dd6-ae30-870255d13c8b"),
                            Description = "Wet Food",
                            Name = "Hearty, chunky, pieces of 84% mercury-free tuna. 1 kilogram of wet food.",
                            Price = 23.45m
                        },
                        new
                        {
                            Id = new Guid("31672b5c-0cc2-472f-ad48-7dbe0e45d4ec"),
                            Description = "It's rainbows and unicorns with our most luxury wet food - literally! Made from 100% queer horse/narwhal hybrids. 1 kilogram of wet food.",
                            Name = "Superpremium Wet Food",
                            Price = 34.56m
                        },
                        new
                        {
                            Id = new Guid("be5ac3ae-7462-409d-aed4-9850b65ff9f0"),
                            Description = "Have your cat eat in style out of this 100% titanium Legacy™ branded food bowl!",
                            Name = "Legacy™ Cat Food Bowl",
                            Price = 45.67m
                        },
                        new
                        {
                            Id = new Guid("15698fdb-b9e8-4492-a9c6-bbd2061130e7"),
                            Description = "Have your cat bother the robot instead of you in the morning! Connect the Legacy™ Automated Cat Feeder to your stupid home IoT network for extra functionality. Singularity kill-switch sold separately.",
                            Name = "Legacy™ Automated Cat Feeder",
                            Price = 56.78m
                        },
                        new
                        {
                            Id = new Guid("f5d1c1af-5665-48eb-96d1-b6e9de9b2d8d"),
                            Description = "Say \"no\" to painful teeth cleanings, and \"Yes!\" to Beigies™ feline dental treats! Pack of 24.",
                            Name = "Beigies™ Rodent-Shaped Dental Treats",
                            Price = 67.89m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
