// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebStore.Database;

#nullable disable

namespace WebStore.Database.Migrations
{
    [DbContext(typeof(WebStoreContext))]
    [Migration("20230505203825_FixWetFoodProductSeed")]
    partial class FixWetFoodProductSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("WebStore.Core.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d3773bf-9ec8-40a6-948e-2e4b192c7438"),
                            Category = "food",
                            Description = "Premium, delicious, kibble made from free range, grass-fed horses. 1 kilogram of kibble.",
                            Name = "Dry Food",
                            Price = 12.34m
                        },
                        new
                        {
                            Id = new Guid("8b3ab2d4-19bf-44db-af92-3c258050da97"),
                            Category = "food",
                            Description = "Hearty, chunky, pieces of 84% mercury-free tuna. 1 kilogram of wet food.",
                            Name = "Wet Food",
                            Price = 23.45m
                        },
                        new
                        {
                            Id = new Guid("a0e28731-5f5c-4b14-b634-a626591ea564"),
                            Category = "food",
                            Description = "It's rainbows and unicorns with our most luxury wet food - literally! Made from 100% queer horse/narwhal hybrids. 1 kilogram of wet food.",
                            Name = "Superpremium Wet Food",
                            Price = 34.56m
                        },
                        new
                        {
                            Id = new Guid("891558b7-3435-4cc8-8d31-fd1892fb679b"),
                            Category = "accessories",
                            Description = "Have your cat eat in style out of this 100% titanium Legacy™ branded food bowl!",
                            Name = "Legacy™ Cat Food Bowl",
                            Price = 45.67m
                        },
                        new
                        {
                            Id = new Guid("fed99aa7-5bea-412b-9148-b9253ac9c7f3"),
                            Category = "accessories",
                            Description = "Have your cat bother the robot instead of you in the morning! Connect the Legacy™ Automated Cat Feeder to your stupid home IoT network for extra functionality. Singularity kill-switch sold separately.",
                            Name = "Legacy™ Automated Cat Feeder",
                            Price = 56.78m
                        },
                        new
                        {
                            Id = new Guid("4dd6fd9a-fb81-4acb-805a-548f96a84c25"),
                            Category = "medical",
                            Description = "Say \"no\" to painful teeth cleanings, and \"Yes!\" to Beigies™ feline dental treats! Pack of 24.",
                            Name = "Beigies™ Rodent-Shaped Dental Treats",
                            Price = 67.89m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
